### PR TITLE
Adding npm and node.js support

### PR DESCRIPTION
**Pull request by alexcastillo**
Adding npm and node.js support

### CODE REVIEW

**Comment by kentmw** [comment]
+1 If my opinion matters.

**Comment by alexcastillo** [comment]
cc @corbanbrook

**Comment by andrewheusser** [comment]
+1

**Comment by Paul-C-F** [comment]
@alexcastillo The package description contains a link to a dead website?

`"description": "Digital Signal Processing for Javascript http://weare.buildingsky.net",`

**Comment by alexcastillo** [comment]
@Paul-C-F that's the website on the repo description.

**Comment by Paul-C-F** [comment]
@alexcastillo I see, since it's corban's url then I guess he has to propose a new one (or decide to get rid of it).

screenshot_82

**Comment by corbanbrook** [comment]
That domain expired years and years ago. :)

**Comment by AlexGustafsson** [comment]
:+1:

**Pull request merged**
